import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import  SideBar from '../components/SideBar';
import Center from '../components/Center';
import Player from '../components/Player';
import { getSession } from 'next-auth/react';


export default function Home() {
  return (
    <div className='flex-grow overflow-y-scroll overflow-hidden'>
      <Head>
        <title>Spotify 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center />
    </div>
  )
}


export async function getServerSideProps(context) {
  const session = await getSession(context);

  return {
    props: {
      session
    }
  }
}