import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import  SideBar from '../components/SideBar';
import Center from '../components/Center';


export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Spotify 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-black h-screen overflow-hidden'>
        <main className='flex'>
          <SideBar/>
          <Center />

          {/* Center Content */}
        </main>
      </div>
      <div>{/*  Player */}</div>
    </div>
  )
}
